export const bannerTag = "DESTACADOS";

export const categories = [
    {
        "id": "all",
        "name": "Todos"
    },
    {
        "id": "2",
        "name": "ESMALTES GEL"
    },
    {
        "id": "3",
        "name": "HERRAMIENTAS"
    },
    {
        "id": "4",
        "name": "LAMPARAS UV"
    },
    {
        "id": "5",
        "name": "IMANES"
    },
    {
        "id": "6",
        "name": "PINCELES"
    },
    {
        "id": "7",
        "name": "ACCESORIOS"
    },
    {
        "id": "8",
        "name": "PINTURA GEL"
    },
    {
        "id": "9",
        "name": "PULIDORAS DE UÑAS"
    },
    {
        "id": "10",
        "name": "POLVO ACRILICO"
    },
    {
        "id": "11",
        "name": "GEL"
    },
    {
        "id": "12",
        "name": "OJO DE GATO"
    },
    {
        "id": "13",
        "name": "PREPARADORES"
    }
];

export const products = [
    {
        "id": 1,
        "sku": "XEI-SETBLUESB",
        "name": "SET DE ESMALTES COLECCION AZULES X6",
        "brand": "XEIJAYI",
        "price": 65,
        "categoryId": "2",
        "image": "1775351516_69d1b6dc37a44.jpg",
        "description": "SET DE 6 ESMALTES CON VARIANTES DE  AZUL- PRESENTACION B DE 15ML - X009 - X010 - X020 - X043 - X045 - X046",
        "etiqueta": null
    },
    {
        "id": 2,
        "sku": "XEI-SETNUDESA-C",
        "name": "SET DE ESMALTES COLORES BASE - COLECCION NUDES X6",
        "brand": "XEIJAYI",
        "price": 65,
        "categoryId": "2",
        "image": "1775352510_69d1babe84687.jpg",
        "description": "SET DE ESMALTES COLORES BASE - NUDES EN PRESENTACION A DE 15ML VARIANTE A",
        "etiqueta": null
    },
    {
        "id": 4,
        "sku": "XEI-SETNUDESA-A",
        "name": "SET DE ESMALTES COLORES BASE - COLECCION NUDES X6",
        "brand": "XEIJAYI",
        "price": 65,
        "categoryId": "2",
        "image": "1775351950_69d1b88e294f7.jpg",
        "description": "SET DE ESMALTES COLORES BASE - COLECCION NUDES PRESENTACION DE 15 ML VARIANTE A",
        "etiqueta": null
    },
    {
        "id": 5,
        "sku": "XEI-SETNUDESA-B",
        "name": "SET DE ESMALTES COLORES BASE - COLECCION NUDES X6",
        "brand": "XEIJAYI",
        "price": 65,
        "categoryId": "2",
        "image": "1775352026_69d1b8da4a5d5.jpg",
        "description": "SET DE ESMALTES COLORES BASE - COLECCION NUDES PRESENTACION DE 15 ML VARIANTE B",
        "etiqueta": null
    },
    {
        "id": 7,
        "sku": "XEI-SETCAKESB",
        "name": "SET DE ESMALTES COLECCION COLORES PASTEL X6",
        "brand": "XEIJAYI",
        "price": 65,
        "categoryId": "2",
        "image": "1775352849_69d1bc1173319.jpg",
        "description": "SET DE ESMALTES COLECCION COLORES PASTEL PRESENTACION B DE 15 ML",
        "etiqueta": null
    },
    {
        "id": 8,
        "sku": "XEI-SETCEGLACIALW",
        "name": "SET DE ESMALTES GEL EFECTO OJO DE GATO COLECCION GLACIAL WATER",
        "brand": "XEIJAYI",
        "price": 75,
        "categoryId": "2",
        "image": "1775354217_69d1c1693504d.jpg",
        "description": "SET DE ESMALTES EN OJO DE GATO COLECCION GLACIAL WATER PRESENTACION DE 15 ML X6",
        "etiqueta": null
    },
    {
        "id": 9,
        "sku": "XEI-SETCEGOLDEN",
        "name": "SET DE ESMALTES GEL EFECTO OJO DE GATO COLECCION GOLDEN",
        "brand": "XEIJAYI",
        "price": 75,
        "categoryId": "2",
        "image": "1775368340_69d1f8946aad9.jpg",
        "description": "SET DE ESMALTES GEL EFECTO OJO DE GATO COLECCION GOLDEN PRESENTACION 15 ML X6（02+03+05+06+07+08)",
        "etiqueta": null
    },
    {
        "id": 10,
        "sku": "XEI-SETREDSUITE",
        "name": "SET DE ESMALTES GEL ROJOS COLECCION X4 RED SUITE",
        "brand": "XEIJAYI",
        "price": 48,
        "categoryId": "2",
        "image": "1775368473_69d1f9190991e.jpg",
        "description": "SET DE ESMALTES GELROJOS COLECCION RED SUITE X4 (M077+M110+M111+M112)",
        "etiqueta": null
    },
    {
        "id": 11,
        "sku": "XEI-SETBRWN-MT",
        "name": "SET DE ESMALTES MARRON CASTAÑO COLECCION CHESTNUT BROWN X6",
        "brand": "XEIJAYI",
        "price": 65,
        "categoryId": "2",
        "image": "1775368717_69d1fa0d92f30.jpg",
        "description": "SET DE ESMALTES MARRON CASTAÑO COLECCION CHESTNUT BROWN X6 (M038 - M041 - M042 - M050 - M077 - M206)",
        "etiqueta": null
    },
    {
        "id": 12,
        "sku": "GLOV-LAMPUV-BLACK",
        "name": "LAMPARA UV PRO TIPO LINTERNA - NEGRA",
        "brand": "GENERICO",
        "price": 18,
        "categoryId": "4",
        "image": "1775369090_69d1fb82a234a.avif",
        "description": "Linterna UV 395NM, Luz Ultravioleta Recargable por USB, Mini Lámpara Portátil para Secado de Esmalte",
        "etiqueta": null
    },
    {
        "id": 13,
        "sku": "XEI-SETCEGEMAS",
        "name": "SET DE ESMALTES EFECTO OJO DE GATO COLECCION GEMAS X6",
        "brand": "XEIJAYI",
        "price": 75,
        "categoryId": "2",
        "image": "1775371734_69d205d61b0df.jpg",
        "description": "ESMALTES EFECTO OJO DE GATO COLECCION GEMAS X6 (ICE CANDY CAT EYE 03 - ICE CANDY CAT EYE 04 - GREEN M202 - GLACIAL BUBBLE 04 - KLEIN BLUE M204 - BLASCKBERRY CAT EYE)",
        "etiqueta": null
    },
    {
        "id": 14,
        "sku": "XEI-SETPRIMAVERA",
        "name": "SET DE ESMALTES COLORES PASTEL COLECCION PRIMAVERA X6",
        "brand": "XEIJAYI",
        "price": 65,
        "categoryId": "2",
        "image": "1775371932_69d2069ca744a.jpg",
        "description": "SET DE ESMALTES PASTELES COLECCION PRIMAVERA X6 PRESENTACION DE 15 ML (M061+M062+M063+M045+M072+M109)",
        "etiqueta": null
    },
    {
        "id": 15,
        "sku": "GLOV-PINSILCN-GREPINK",
        "name": "PINCELES DE SILICONE X2 VERDE Y ROSADO",
        "brand": "GLOVE",
        "price": 16,
        "categoryId": "3",
        "image": "1775373816_69d20df896f35.jpg",
        "description": "2 UNIDADES DE PINCELES DE SILICONE (1 VERDE + 1 ROSADO)",
        "etiqueta": null
    },
    {
        "id": 16,
        "sku": "GLOV-IMANESFR",
        "name": "IMAN PARA EFECTO OJO DE GATO DOBLE PUNTA CON ESFERA SILVER",
        "brand": "GLOVE",
        "price": 18,
        "categoryId": "5",
        "image": "1775431059_69d2ed93d92ce.jpg",
        "description": "Barra Iman de manicura de doble punta mejorada | Herramienta de diseño de ojo de gato de hierro con bolas de acero redondas, efecto de ojo de gato 3D, adecuada para salones de manicura y para el hogar.",
        "etiqueta": null
    },
    {
        "id": 17,
        "sku": "XEI-CEBLACKBRRY",
        "name": "ESMALTE EN GEL CON EFECTO OJO DE GATO COLOR ROJO PROFUNDO BLACKBERRY",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1775435740_69d2ffdcaa6ee.jpg",
        "description": "ESMALTE EN OJO DE GATO ROJO PROFUNDO (BLACKBERRY) PRESENTACION A DE 15ML",
        "etiqueta": null
    },
    {
        "id": 18,
        "sku": "XEI-TPCTCLEAR100ML",
        "name": "XEIJAYI TOP COAT GLASS CLEAR - PRESENTACION 100 ML",
        "brand": "XEIJAYI",
        "price": 50,
        "categoryId": "11",
        "image": "1775435867_69d3005b2b953.jpg",
        "description": "TOP COAT GLASS DE LA MARCA XEIJAYI EN PRESENTACION DE 100 ML",
        "etiqueta": null
    },
    {
        "id": 19,
        "sku": "XEI-BUILDERG100ML",
        "name": "XEIJAYI BUILDER GEL - PRESENTACION 100 ML",
        "brand": "XEIJAYI",
        "price": 50,
        "categoryId": "2",
        "image": "1775522567_69d45307bf30b.jpg",
        "description": "XEIJAYI BUILDER GEL - PRESENTACION 100 ML",
        "etiqueta": null
    },
    {
        "id": 20,
        "sku": "XEI-CERUBIRED",
        "name": "ESMALTE EN GEL OJO DE GATO ROJO RUBI",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1775523581_69d456fd8b3cb.jpg",
        "description": "ESMALTE EN OJO DE GATO ROJO RUBI PRESENTACION DE 15 ML",
        "etiqueta": null
    },
    {
        "id": 21,
        "sku": "XEI-SETBROWNSB",
        "name": "SET DE ESMALTES COLECCION MARRONES X6",
        "brand": "XEIJAYI",
        "price": 65,
        "categoryId": "2",
        "image": "1775523792_69d457d058931.jpg",
        "description": "SET DE ESMALTES EN GEL COLECCION MARRONES PRESENTACION B X6 DE 15ML - X005 - X006 - X007 - X011 -X 022 -X 032",
        "etiqueta": null
    },
    {
        "id": 22,
        "sku": "XEI-CEGLDNPEARL",
        "name": "ESMALTE GEL OJO DE GATO GOLDEN PEARL",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1775525067_69d45ccb57521.jpg",
        "description": "ESMALTE EN GEL DORADO PERLADO PRESENTACION A DE 15ML",
        "etiqueta": null
    },
    {
        "id": 23,
        "sku": "XEI-CEWHTMOONLGHT",
        "name": "ESMALTE GEL OJO DE GATO LUZ DE LUNA BLANCO",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1775525160_69d45d282d3cc.jpg",
        "description": "ESMALTE GEL OJO DE GATO LUZ DE LUNA BLANCO",
        "etiqueta": null
    },
    {
        "id": 24,
        "sku": "XEI-CEROCKSUGR01",
        "name": "ESMALTE GEL OJO DE GATO ROCK SUGAR 01",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1775526364_69d461dc14249.jpg",
        "description": "ESMALTE EN GEL OJO DE GATO DE LA COLECCION ROCK SUGAR (01)",
        "etiqueta": null
    },
    {
        "id": 25,
        "sku": "XEI-BLACKPEARL",
        "name": "ESMALTE GEL OJO DE GATO NEGRO PERLADO - BLACK PEARL",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1775526481_69d462514008c.jpg",
        "description": "ESMALTE EN GEL OJON DE GATO NEGRO PERLADO - BLACK PEARL",
        "etiqueta": null
    },
    {
        "id": 26,
        "sku": "XEI-SETGLITTERB",
        "name": "SET DE ESMALTES COLECCION GLITTER X6 -X034 - X036 - X038 - X040 - X041 - X058",
        "brand": "XEIJAYI",
        "price": 65,
        "categoryId": "2",
        "image": "1775527047_69d4648772ad1.jpg",
        "description": "SET DE ESMALTES COLECCION GLITTER X6",
        "etiqueta": null
    },
    {
        "id": 27,
        "sku": "XEI-BASERUBBRFIB",
        "name": "XEIJAYI BASE RUBBER FIBER - TRANSPARENTE 15ML",
        "brand": "XEIJAYI",
        "price": 20,
        "categoryId": "11",
        "image": "1775527129_69d464d95fa28.jpg",
        "description": "XEIJAYI BASE RUBBER FIBER - TRANSPARENTE 15ML",
        "etiqueta": null
    },
    {
        "id": 28,
        "sku": "XEI-SETDOPAMINA",
        "name": "SET ESMALTES GEL OJO DE GATO DOPAMINA",
        "brand": "XEIJAYI",
        "price": 75,
        "categoryId": "12",
        "image": "1775532235_69d478cb5ee1e.jpg",
        "description": "SET DE ESMALTES EN GEL OJO DE GATO COLECCION DOPAMINA",
        "etiqueta": null
    },
    {
        "id": 29,
        "sku": "GLOV-PINSILCN-8PCSRAN",
        "name": "PINCELES DE SILICONE X8 COLORES RANDOM",
        "brand": "GLOVE",
        "price": 22,
        "categoryId": "3",
        "image": "1775532794_69d47afaadf1b.jpg",
        "description": "SET DE 8 PINCELES PARA DECORACIÓN DE UÑAS, BOLÍGRAFOS DE MANICURA VERSÁTILES PARA GEL, DETALLES Y DISEÑOS FLORALES, APLICADORES DE PLÁSTICO DE GRADO PROFESIONAL PARA LA CREACIÓN DE ARTE DE UÑAS.",
        "etiqueta": null
    },
    {
        "id": 30,
        "sku": "XEI-CEREDWINE",
        "name": "ESMALTE GEL OJO DE GATO RED WINE",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1775537076_69d48bb41a41d.jpg",
        "description": "ESMALTE GEL OJO DE GATO RED WINE PRESENTACION A DE 15ML",
        "etiqueta": null
    },
    {
        "id": 31,
        "sku": "XEI-CEDARKPLUM",
        "name": "ESMALTE GEL OJO DE GATO ROJO DARK PLUM",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1775537248_69d48c60e228b.jpg",
        "description": "ESMALTE GEL OJO DE GATO ROJO CIRUELA EBANO",
        "etiqueta": null
    },
    {
        "id": 32,
        "sku": "XEI-CEDARKRED",
        "name": "ESMALTE GEL OJO DE GATO DARK RED",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1775537345_69d48cc15ad0e.jpg",
        "description": "ESMALTE GEL OJO DE GATO DARK RED",
        "etiqueta": null
    },
    {
        "id": 33,
        "sku": "XEI-CEFIREWORKS",
        "name": "ESMALTE GEL OJO DE GATO ROJO FIRE WORKS",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1775537453_69d48d2dde06d.jpg",
        "description": "ESMALTE GEL OJO DE GATO ROJO FIRE WORKS",
        "etiqueta": null
    },
    {
        "id": 34,
        "sku": "XEI-CEPINKSFRAMB",
        "name": "ESMALTE GEL OJO DE GATO ROJO FRAMBUESA",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1775537549_69d48d8d861b0.jpg",
        "description": "ESMALTE GEL OJO DE GATO ROJO FRAMBUESA",
        "etiqueta": null
    },
    {
        "id": 35,
        "sku": "XEIM001-MILKWHITE",
        "name": "ESMALTE EN GEL BLANCO LECHOSO XEIJAYI - M001",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776231220_69df2334b34d8.jpg",
        "description": "ESMALTE EN GEL XEIJAYI BLANCO LECHOSO XEIJAYI - M001",
        "etiqueta": null
    },
    {
        "id": 36,
        "sku": "XEIM032-VERDENAVID-M032",
        "name": "VERDE NAVIDAD XEIJAYI - M032",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776232413_69df27ddd16d4.jpg",
        "description": "VERDE NAVIDAD XEIJAYI - M032",
        "etiqueta": null
    },
    {
        "id": 37,
        "sku": "XEIM042-MARRONOSCURO",
        "name": "MARRON CHOCOLATE XEIJAYI - M042",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776233423_69df2bcfd1c83.jpg",
        "description": "MARRON CHOCOLATE XEIJAYI - M042",
        "etiqueta": null
    },
    {
        "id": 38,
        "sku": "XEIM041-MARRONLATE",
        "name": "MARRON CHOCOLATE XEIJAYI - M041",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776289493_69e006d518e0a.jpg",
        "description": "MARRON CHOCOLATE XEIJAYI - M041",
        "etiqueta": null
    },
    {
        "id": 40,
        "sku": "XEIM040-MARRONCHOCO",
        "name": "MARRON LATE XEIJAYI - M040",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776289641_69e007691f5cd.jpg",
        "description": "MARRON CHOCOLATE XEIJAYI - M040",
        "etiqueta": null
    },
    {
        "id": 41,
        "sku": "XEIM039-MARRON",
        "name": "MARRON CREMA XEIJAYI - M039",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776289904_69e00870397fa.jpg",
        "description": "MARRON CREMA XEIJAYI - M039",
        "etiqueta": null
    },
    {
        "id": 42,
        "sku": "XEIM043-MARRONVINTG",
        "name": "XEIJAYI MARRON VINTAGE - M043",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776290014_69e008dee501c.jpg",
        "description": "XEIJAYI MARRON VINTAGE - M043",
        "etiqueta": null
    },
    {
        "id": 43,
        "sku": "XEIM038-MARRONMILK",
        "name": "XEIJAYI MARRON LECHE - M038",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776290190_69e0098ed248c.jpg",
        "description": "XEIJAYI MARRON LECHE - M038",
        "etiqueta": null
    },
    {
        "id": 44,
        "sku": "XEIM037-CELESTEBABY",
        "name": "XEIJAYI CELESTE BEBE - BLUE BABY - M037",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776290307_69e00a037f562.jpg",
        "description": "XEIJAYI CELESTE BEBE - BLUE BABY - M037",
        "etiqueta": null
    },
    {
        "id": 45,
        "sku": "XEIM036-PEACOCKBLUE",
        "name": "XEIJAYI AZUL ELECTRICO - PEACOCK BLUE - M036",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776290414_69e00a6e7df8d.jpg",
        "description": "XEIJAYI AZUL ELECTRICO - PEACOCK BLUE - M036",
        "etiqueta": null
    },
    {
        "id": 46,
        "sku": "XEIM035-ZAFIROBLUE",
        "name": "XEIJAYI AZUL CYAN - M035",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776290530_69e00ae2a3845.jpg",
        "description": "XEIJAYI AZUL CYAN - M035",
        "etiqueta": null
    },
    {
        "id": 47,
        "sku": "XEIM034-CELESTE",
        "name": "XEIJAYI CELESTE MENTA - M034",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776290673_69e00b71d0391.jpg",
        "description": "XEIJAYI CELESTE MENTA - M034",
        "etiqueta": null
    },
    {
        "id": 48,
        "sku": "XEIM033-TURQUESA-M033",
        "name": "XEIJAYI TURQUESA AZULADO - M033",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776290807_69e00bf7ef1c2.jpg",
        "description": "XEIJAYI TURQUESA AZULADO - M033",
        "etiqueta": null
    },
    {
        "id": 49,
        "sku": "XEIM031-DARKGREEN",
        "name": "XEIJAYI VERDE OSCURO - M031",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776290874_69e00c3a3e011.jpg",
        "description": "XEIJAYI VERDE OSCURO - M031",
        "etiqueta": null
    },
    {
        "id": 50,
        "sku": "XEI-M030OLIVEGREEN",
        "name": "XEIJAYI VERDE OLIVA - M030",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776290961_69e00c918d4db.jpg",
        "description": "XEIJAYI VERDE OLIVA - M030",
        "etiqueta": null
    },
    {
        "id": 51,
        "sku": "XEI-VERDEMINT-M029",
        "name": "XEIJAYI VERDE MENTA - M029",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776291196_69e00d7c8745e.jpg",
        "description": "XEIJAYI VERDE MENTA - M029",
        "etiqueta": null
    },
    {
        "id": 52,
        "sku": "XEI-OLIVEFOREST-M028",
        "name": "XEIJAYI VERDE OLIVA BOSQUE - M028",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776291789_69e00fcd88aaa.jpg",
        "description": "XEIJAYI VERDE OLIVA BOSQUE - M028",
        "etiqueta": null
    },
    {
        "id": 53,
        "sku": "XEIM027-VERDELATE",
        "name": "XEIJAYI VERDE LATE - M027",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776298262_69e02916b5831.jpg",
        "description": "XEIJAYI VERDE LATE - M027",
        "etiqueta": null
    },
    {
        "id": 54,
        "sku": "XEIM026-YELLOWGALANT",
        "name": "XEIJAYI AMARILLO ELEGANTE - M026",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776298483_69e029f37275d.jpg",
        "description": "XEIJAYI AMARILLO ELEGANTE - M026",
        "etiqueta": null
    },
    {
        "id": 55,
        "sku": "XEIM025-MATCHGREEN",
        "name": "XEIJAYI VERDE CREMOSO - M025",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776298914_69e02ba29f5a0.jpg",
        "description": "XEIJAYI VERDE CREMOSO - M025",
        "etiqueta": null
    },
    {
        "id": 56,
        "sku": "XEIM044-ELEGANTBROWN",
        "name": "XEIJAYI MARRON ELEGANTE - M044",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776299066_69e02c3a84b04.jpg",
        "description": "XEIJAYI MARRON ELEGANTE - M044",
        "etiqueta": null
    },
    {
        "id": 57,
        "sku": "XEIM045-GREYLIGTH",
        "name": "XEIJAYI GRIS CLARO - M045",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776299155_69e02c93b94e0.jpg",
        "description": "XEIJAYI GRIS CLARO - M045",
        "etiqueta": null
    },
    {
        "id": 58,
        "sku": "XEIM047-GREYQUARTZ",
        "name": "XEIJAYI GRIS CUARZO - M047",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776299312_69e02d300739e.jpg",
        "description": "XEIJAYI GRIS CUARZO - M047",
        "etiqueta": null
    },
    {
        "id": 59,
        "sku": "XEIM048-GREYMILKTEA",
        "name": "XEIJAYI GRIS - M048",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776299411_69e02d935b9b6.jpg",
        "description": "XEIJAYI GRIS - M048",
        "etiqueta": null
    },
    {
        "id": 60,
        "sku": "XEIM050-BLACKPURE",
        "name": "XEIJAYI NEGRO - M050",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776299671_69e02e9704b4f.jpg",
        "description": "XEIJAYI NEGRO - M050",
        "etiqueta": null
    },
    {
        "id": 61,
        "sku": "XEI-WHITEPURE-M061",
        "name": "XEIJAYI BLANCO - M061",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776299749_69e02ee50bb72.jpg",
        "description": "XEIJAYI BLANCO - M061",
        "etiqueta": null
    },
    {
        "id": 62,
        "sku": "XEI-BONEWHITE-M062",
        "name": "XEIJAYI BLANCO HUESO - M062",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776299911_69e02f875f1ad.jpg",
        "description": "XEIJAYI BLANCO HUESO - M062",
        "etiqueta": null
    },
    {
        "id": 63,
        "sku": "XEI-VAINILLA-M063",
        "name": "XEIJAYI VAINILLA - M063",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776300049_69e030113038d.jpg",
        "description": "XEIJAYI VAINILLA - M063",
        "etiqueta": null
    },
    {
        "id": 64,
        "sku": "XEI-YELLOW-M064",
        "name": "XEIJAYI AMARILLO - M064",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776300223_69e030bf38d11.jpg",
        "description": "XEIJAYI AMARILLO - M064",
        "etiqueta": null
    },
    {
        "id": 65,
        "sku": "XEI-YELLOWLITGH-M065",
        "name": "XEIJAYI AMARILLO CLARO - M065",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776300298_69e0310ad4ade.jpg",
        "description": "XEIJAYI AMARILLO CLARO - M065",
        "etiqueta": null
    },
    {
        "id": 66,
        "sku": "XEI-YELLOWORANGE-M066",
        "name": "XEIJAYI AMARILLO CITRICO - M066",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776300934_69e0338659056.jpg",
        "description": "XEIJAYI AMARILLO CITRICO - M066",
        "etiqueta": null
    },
    {
        "id": 67,
        "sku": "XEI-BROWNDELICACY-MO69",
        "name": "XEIJAYI MARRON DELICACY - M069",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776301183_69e0347fc535d.jpg",
        "description": "XEIJAYI MARRON DELICACY - M069",
        "etiqueta": null
    },
    {
        "id": 68,
        "sku": "XEI-MILKBEIGE-M070",
        "name": "XEIJAYI MARRON MILKSHAKE - M070",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776301299_69e034f375858.jpg",
        "description": "XEIJAYI MARRON MILKSHAKE - M070",
        "etiqueta": null
    },
    {
        "id": 69,
        "sku": "XEI-PINKSUGAR-M072",
        "name": "XEIJAYI ROSADO SUGAR - M072",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776301398_69e03556cd5f9.jpg",
        "description": "XEIJAYI ROSADO SUGAR - M072",
        "etiqueta": null
    },
    {
        "id": 70,
        "sku": "XEI-ORANGE-M074",
        "name": "XEIJAYI NARANJA - M074",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776301528_69e035d85bb47.jpg",
        "description": "XEIJAYI NARANJA - M074",
        "etiqueta": null
    },
    {
        "id": 71,
        "sku": "XEI-TERRACOTA-M075",
        "name": "XEIJAYI TERRACOTA - M075",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776301633_69e036414e9b8.jpg",
        "description": "XEIJAYI TERRACOTA - M075",
        "etiqueta": null
    },
    {
        "id": 72,
        "sku": "XEI-CAPUCCINO-M076",
        "name": "XEIJAYI MARRON CAPUCCINO - M076",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776301746_69e036b28580f.jpg",
        "description": "XEIJAYI MARRON CAPUCCINO - M076",
        "etiqueta": null
    },
    {
        "id": 73,
        "sku": "XEI-BURDEOSRED-M077",
        "name": "XEIJAYI ROJO BURDEOS- M077",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776302058_69e037eabac77.jpg",
        "description": "XEIJAYI ROJO BURDEOS - M077",
        "etiqueta": null
    },
    {
        "id": 74,
        "sku": "XEI-REDTILE-M078",
        "name": "XEIJAYI ROJO TEJA - M078",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776302147_69e03843a712f.jpg",
        "description": "XEIJAYI ROJO TEJA - M078",
        "etiqueta": null
    },
    {
        "id": 75,
        "sku": "XEI-REDSINGULAR-M080",
        "name": "XEIJAYI ROJO - M080",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776302225_69e03891eb042.jpg",
        "description": "XEIJAYI ROJO - M080",
        "etiqueta": null
    },
    {
        "id": 76,
        "sku": "XEI-REDCAPSICUM-M081",
        "name": "XEIJAYI ROJO PIMIENTO - M081",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776302414_69e0394e0d374.jpg",
        "description": "XEIJAYI ROJO PIMIENTO - M081",
        "etiqueta": null
    },
    {
        "id": 77,
        "sku": "XEI-DEEPRED-M082",
        "name": "XEIJAYI ROJO PROFUNDO - M082",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776302494_69e0399e0af3f.jpg",
        "description": "XEIJAYI ROJO PROFUNDO - M082",
        "etiqueta": null
    },
    {
        "id": 78,
        "sku": "XEI-REDCHERRY-M083",
        "name": "XEIJAYI ROJO CEREZA - M083",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776302572_69e039ec4838c.jpg",
        "description": "XEIJAYI ROJO CEREZA - M083",
        "etiqueta": null
    },
    {
        "id": 79,
        "sku": "XEI-REDPLUM-M084",
        "name": "XEIJAYI VINO ROJO CIRUELA - M084",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776302748_69e03a9cf2210.jpg",
        "description": "XEIJAYI VINO ROJO CIRUELA - M084",
        "etiqueta": null
    },
    {
        "id": 80,
        "sku": "XEI-MALVAPINK-M086",
        "name": "XEIJAYI ROSADO MALVA - M086",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776303306_69e03cca7ce5b.jpg",
        "description": "XEIJAYI ROSADO MALVA - M086",
        "etiqueta": null
    },
    {
        "id": 81,
        "sku": "XEI-PURPLECREAM-M088",
        "name": "XEIJAYI LILA CREAM - M088",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776370496_69e14340c4c6a.jpg",
        "description": "XEIJAYI LILA CREAM - M088",
        "etiqueta": null
    },
    {
        "id": 82,
        "sku": "XEI-PURPLELIGTH-M089",
        "name": "XEIJAYI PURPURA CENIZA - M089",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776371145_69e145c9ddf7b.jpg",
        "description": "XEIJAYI PURPURA CENIZA - M089",
        "etiqueta": null
    },
    {
        "id": 83,
        "sku": "XEI-VIOLETDUST-M090",
        "name": "XEIJAYI VIOLETA CENIZO - M090",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776371308_69e1466cd91a0.jpg",
        "description": "XEIJAYI VIOLETA CENIZO - M090",
        "etiqueta": null
    },
    {
        "id": 84,
        "sku": "XEI-PURPLEDARK-M091",
        "name": "XEIJAYI PURPURA - M091",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776371370_69e146aabcc3e.jpg",
        "description": "XEIJAYI PURPURA - M091",
        "etiqueta": null
    },
    {
        "id": 85,
        "sku": "XEI-BLUEBERRY-M092",
        "name": "XEIJAYI AZUL ARANDANO - M092",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776371535_69e1474f8c310.jpg",
        "description": "XEIJAYI AZUL ARANDANO - M092",
        "etiqueta": null
    },
    {
        "id": 86,
        "sku": "XEI-VOLCANICBLUE-M093",
        "name": "XEIJAYI AZUL VOLCANICO - M093",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776371640_69e147b85463f.jpg",
        "description": "XEIJAYI AZUL VOLCANICO - M093",
        "etiqueta": null
    },
    {
        "id": 87,
        "sku": "XEI-REALBLUE-M094",
        "name": "XEIJAYI AZUL REAL - M094",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776372390_69e14aa693000.jpg",
        "description": "XEIJAYI AZUL REAL - M094",
        "etiqueta": null
    },
    {
        "id": 88,
        "sku": "XEI-BLUEDEEP-095",
        "name": "XEIJAYI AZUL PROFUNDO - M095",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776372611_69e14b837af5c.jpg",
        "description": "XEIJAYI AZUL PROFUNDO - M095",
        "etiqueta": null
    },
    {
        "id": 89,
        "sku": "XEI-BLUESKY-M096",
        "name": "XEIJAYI AZUL CIELO - M096",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776372744_69e14c0869399.jpg",
        "description": "XEIJAYI AZUL CIELO - M096",
        "etiqueta": null
    },
    {
        "id": 90,
        "sku": "XEI-TURQUESAVINTAGE-M099",
        "name": "XEIJAYI AZUL TURQUESA CARIBE - M099",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776372922_69e14cba3e320.jpg",
        "description": "XEIJAYI AZUL TURQUESA CARIBE - M099",
        "etiqueta": null
    },
    {
        "id": 91,
        "sku": "XEI-BALLETPINK-M109",
        "name": "XEIJAYI ROSADO BALLET - M109",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776373372_69e14e7cd43dd.jpg",
        "description": "XEIJAYI ROSADO BALLET - M109",
        "etiqueta": null
    },
    {
        "id": 92,
        "sku": "XEI-JELLYRED-M112",
        "name": "XEIJAYI JELLY ROJO SHEER NUDE - M112",
        "brand": "XEIJAYI",
        "price": 16,
        "categoryId": "2",
        "image": "1776383638_69e17696a4f0e.jpg",
        "description": "XEIJAYI JELLY ROJO SHEER NUDE - M112",
        "etiqueta": null
    },
    {
        "id": 93,
        "sku": "XEI-CHEESEYELLOW-M119",
        "name": "XEIJAYI AMARILLO PALIDO CHEESE YELLOW - M119",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776383751_69e17707a85e9.jpg",
        "description": "XEIJAYI AMARILLO PALIDO CHEESE YELLOW - M119",
        "etiqueta": null
    },
    {
        "id": 94,
        "sku": "XEI-MACARONPINK-M121",
        "name": "XEIJAYI ROSADO PASTEL - M121",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776383826_69e177526d7be.jpg",
        "description": "XEIJAYI ROSADO PASTEL - M121",
        "etiqueta": null
    },
    {
        "id": 95,
        "sku": "XEI-YELLOWSUN-M178",
        "name": "XEIJAYI AMARILLO SOLAR - M178",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1776384000_69e17800aa5e5.jpg",
        "description": "XEIJAYI AMARILLO SOLAR - M178",
        "etiqueta": null
    },
    {
        "id": 96,
        "sku": "LAM-TRASNFLOWERSBN-001",
        "name": "LAMINA DE TRANSFERENCIA PARA UÑAS CON DISEÑO DE ENCAJE FLORAL EN BLANCO Y NEGRO",
        "brand": "GLOVE",
        "price": 14,
        "categoryId": "7",
        "image": "1776730695_69e6c247399de.jpg",
        "description": "1 Caja de 10 Rollos de Elegante Lámina de Transferencia para Uñas con Diseño de Encaje Floral en Blanco y , Pegatinas de Papel Vintage con Cielo Estrellado y Flores, Accesorios y Herramientas para Decoración de Uñas",
        "etiqueta": null
    },
    {
        "id": 97,
        "sku": "BRTAVIZVY-GELPAINT-01",
        "name": "GEL DE PINTURA DE 9 COLORES BRTAVIZVY -01",
        "brand": "BRTAVIZVY",
        "price": 32,
        "categoryId": "8",
        "image": "1776731183_69e6c42f59a22.jpg",
        "description": "Gel de pintura de 9 colores para masaje, nueve cuadrículas de palacio, alta saturación, lavado engradado de tinte, gel de dibujo de color marrón rojizo otoñal, color de caramelo, esmalte de uñas en gel LED",
        "etiqueta": null
    },
    {
        "id": 98,
        "sku": "BRTAVIZVY-GELPAINT-02",
        "name": "GEL DE PINTURA DE 9 COLORES BRTAVIZVY - 02",
        "brand": "BRTAVIZVY",
        "price": 32,
        "categoryId": "8",
        "image": "1776731270_69e6c48644817.jpg",
        "description": "Gel de pintura de 9 colores para masaje, nueve cuadrículas de palacio, alta saturación, lavado engradado de tinte, gel de dibujo de color marrón rojizo otoñal, color de caramelo, esmalte de uñas en gel LED",
        "etiqueta": null
    },
    {
        "id": 99,
        "sku": "JILLRADIA-GELPAINT-01",
        "name": "GEL DE PINTURA DE 9 COLORES JILLRADIA - 01",
        "brand": "JILLRADIA",
        "price": 32,
        "categoryId": "8",
        "image": "1776731555_69e6c5a3ee0cc.jpg",
        "description": "JILLRADIA PEGAMENTO PARA GOLPEAR DE 9 COLORES, MANCHADO EN LATA, DE ALTA SATURACIÓN, POPULAR, SEMISÓLIDO, PARA UÑAS, PARA MUJER, PARA MANICURA DE SALÓN Y BRICOLAJE",
        "etiqueta": null
    },
    {
        "id": 100,
        "sku": "TIPS-MISSCHDMND3D",
        "name": "TIPS SOFTGEL MISSCHEERING 120 PCS 3D ALMOND - 03",
        "brand": "MISSCHEERING",
        "price": 28,
        "categoryId": "7",
        "image": "1776731963_69e6c73b7e8b7.jpg",
        "description": "120\/140 UÑAS POSTIZAS ACRÍLICAS ARTIFICIALES EN FORMA DE ALMENDRA Y DIAMANTE PARA BALLET, TIPO BALLET",
        "etiqueta": null
    },
    {
        "id": 101,
        "sku": "JILLRADIA-GELPAINT-PINK",
        "name": "GEL DE PINTURA DE 9 COLORES ROSADOS JILLRADIA - PINK",
        "brand": "JILLRADIA",
        "price": 32,
        "categoryId": "8",
        "image": "1776732776_69e6ca682a609.jpg",
        "description": "SERIE NUEVA DE ESMALTE EN GEL SÓLIDO ROSA NUDE SUAVE DE 9 COLORES, ESMALTE EN GEL VERSÁTIL PARA CREAR EFECTOS DE DEGRADADO, PERFECTO PARA DISEÑOS DE ARTE DE UÑAS DE MODA DE SALÓN CON UN BRILLO LUSTROSO, LA ELECCIÓN IDEAL PARA EL CUIDADO DE UÑAS DE MUJER",
        "etiqueta": null
    },
    {
        "id": 102,
        "sku": "MORDDA-GELPAINT-12",
        "name": "GEL DE PINTURA DE 12 COLORES VARIOS - MORDDA",
        "brand": "MORDDA",
        "price": 38,
        "categoryId": "8",
        "image": "1776733048_69e6cb78ec2d4.jpg",
        "description": "MORDDA 12 COLORES NUEVO POPULAR GEL SÓLIDO PARA UÑAS GEL SEMI PERMANENTE UÑAS ARTÍSTICAS REMOJO GEL LED MANICURA DE NAVIDAD REGALO SALÓN DE UÑAS MANICURA",
        "etiqueta": null
    },
    {
        "id": 103,
        "sku": "JILLRADIA-GELPAINT-CATEYESP",
        "name": "GEL DE PINTURA DE 9 COLORES OJO DE GATO JILLRADIA - PURPLE",
        "brand": "JILLRADIA",
        "price": 32,
        "categoryId": "8",
        "image": "1776733274_69e6cc5ae0f2c.jpg",
        "description": "KIT DE ESMALTE DE UÑAS EN GEL EFECTO OJO DE GATO SÓLIDO MORADO JILLRADIA DE 9 COLORES, POLVO MAGNÉTICO DE ALTA DENSIDAD, FÁCIL DE USAR PARA UN ARTE DE UÑAS IMPRESIONANTE EN CASA, KIT DE INICIO DIY PARA PRINCIPIANTES Y PROFESIONALES.",
        "etiqueta": null
    },
    {
        "id": 104,
        "sku": "JILLRADIA-GELPAINT-BROWNS",
        "name": "GEL DE PINTURA DE 9 COLORES MARRONES JILLRADIA - BROWNS",
        "brand": "JILLRADIA",
        "price": 32,
        "categoryId": "8",
        "image": "1776733447_69e6cd073aeb1.jpg",
        "description": "JILLRADIA GEL DE UÑAS EN GEL SÓLIDO SEMIPERMANENTE PARA ARTE DE UÑAS, NUEVO Y POPULAR, EN 9 COLORES, GEL DE INMERSIÓN LED, REGALO DE MANICURA DE NAVIDAD PARA SALÓN DE UÑAS, MANICURA DIY",
        "etiqueta": null
    },
    {
        "id": 105,
        "sku": "XEI-SETBUBBLESWEET",
        "name": "SET ESMALTES GEL OJO DE GATO BUBBLE SWEET SUMMER",
        "brand": "XEIJAYI",
        "price": 75,
        "categoryId": "12",
        "image": "1776735184_69e6d3d057192.jpg",
        "description": "CONJUNTO DE UÑAS CAT EYE GEL MAGNÉTICO REFLECTANTE HOLOGRÁFICO EN 6 COLORES (M183 - M184 - M185 - M186 - M187 - M188), 15ML",
        "etiqueta": null
    },
    {
        "id": 107,
        "sku": "XEI-SETPINKSB",
        "name": "SET DE ESMALTES COLECCION ROSADOS X6",
        "brand": "XEIJAYI",
        "price": 65,
        "categoryId": "2",
        "image": "1776735651_69e6d5a373834.jpg",
        "description": "ESMALTE DE UÑAS DE VERANO ENCANTADOR MANICURA DE TEMPORADA SET DE 6 COLORES 15ML ESMALTE DE UÑAS SOAK-OFF LED ESMALTE DE UÑAS SALÓN MUJER HERRAMIENTAS DE MANICURA MODA DE LAS CUATRO ESTACIONES - X033 - X057 - X060 - X061 -X062 - X063",
        "etiqueta": null
    },
    {
        "id": 108,
        "sku": "XEI-SETJELLYAMBER",
        "name": "SET DE ESMALTES COLORES JELLYS COLECCION JELLY AMBER X6",
        "brand": "XEIJAYI",
        "price": 65,
        "categoryId": "2",
        "image": "1776736257_69e6d80104cf1.jpg",
        "description": "XEIJAYI KIT DE UÑAS EN MARCO BOTELLA ÁMBAR 6 COLORES - KIT DE UÑAS DE OTOÑO E INVIERNO A LA MODA CON GEL DE UÑAS ULTRA BRILLANTE SERIE ÁMBAR DE 6 COLORES. GEL LED MODERNO, FÁCIL Y VERSÁTIL CON UN ACABADO BRILLANTE\r\n6 PIEZAS (101+102+103+136+137+138",
        "etiqueta": null
    },
    {
        "id": 109,
        "sku": "HER-DRILL45KRPMPRO-ROS",
        "name": "PULIDORA DE UÑAS PROFESIONAL 45.000 RPM - ROSA",
        "brand": "GENERICO",
        "price": 145,
        "categoryId": "3",
        "image": "1776801714_69e7d7b23a62e.jpg",
        "description": "MÁQUINA ELÉCTRICA PULIDORA PARA UÑAS DE 45000 RPM CON PANTALLA HD, LIMA ELÉCTRICA, PLUMA DE MANICURA DE METAL, TORNO PROFESIONAL PARA UÑAS, LIJADORA, DRILL",
        "etiqueta": "DESTACADOS"
    },
    {
        "id": 110,
        "sku": "ACC-CUADRIPERLAS-12",
        "name": "PERLAS BLANCAS SEMICIRCULAR DE 12 CUADRÍCULAS - CAJA 6 TAMAÑOS",
        "brand": "GENERICO",
        "price": 12,
        "categoryId": "7",
        "image": "1776802062_69e7d90e89a41.jpg",
        "description": "ACCESORIOS DE ARTE DE UÑAS DE PERLA BLANCA SEMICIRCULAR DE 12 CUADRÍCULAS, RHINESTONES DE UÑAS, DECORACIONES DE UÑAS",
        "etiqueta": null
    },
    {
        "id": 111,
        "sku": "ACR-WMFL1-01",
        "name": "POLVO ACRÍLICO TRANSPARENTE NOCIS - PROFESIONAL PARA UÑAS - 60 G - 2 ONZ",
        "brand": "NOCIS",
        "price": 24,
        "categoryId": "10",
        "image": "1776802849_69e7dc21d755d.jpg",
        "description": "POLVO ACRÍLICO TRANSPARENTE CLEAR - KIT DE 60 GRAMOS DE POLVO ACRÍLICO PROFESIONAL PARA UÑAS PARA EXTENSIÓN Y FORTALECIMIENTO, SUMINISTROS DE MANICURA FRANCESA CON ESCULPIDURA 3D, NAIL ART",
        "etiqueta": null
    },
    {
        "id": 112,
        "sku": "ACR-WMFL1-02",
        "name": "POLVO ACRÍLICO BLANCO NOCIS - PROFESIONAL PARA UÑAS - 60 G - 2 ONZ",
        "brand": "NOCIS",
        "price": 24,
        "categoryId": "10",
        "image": "1776802935_69e7dc7753936.jpg",
        "description": "POLVO ACRÍLICO BLANCO - KIT DE 60 GRAMOS DE POLVO ACRÍLICO PROFESIONAL PARA UÑAS PARA EXTENSIÓN Y FORTALECIMIENTO, SUMINISTROS DE MANICURA FRANCESA CON ESCULPIDURA 3D, NAIL ART",
        "etiqueta": null
    },
    {
        "id": 113,
        "sku": "XEI-BLOOMINGEL-01",
        "name": "BLOOMING GEL EFECTO - XEIJAYI 15 ML",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "11",
        "image": "1776803711_69e7df7f3b349.jpg",
        "description": "UNIDAD DE 15ML DE GEL DE UÑAS NUEVO Y POPULAR, SEMI PERMANENTE, PARA REMOJO, LED, SALÓN DE UÑAS, GEL PARA UÑAS",
        "etiqueta": null
    },
    {
        "id": 114,
        "sku": "XEI-CELUXCOFF-03",
        "name": "ESMALTE GEL OJO DE GATO MARRON CAFE LUXURY - 03",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1776805651_69e7e71325d91.jpg",
        "description": "XEIJAYI 15ML GEL MAGNÉTICO SEMI PERMANENTE OJO DE GATO REFLECTANTE PARA UÑAS, ARTE DE UÑAS LED, GEL PARA SALÓN DE MANICURA DIY",
        "etiqueta": null
    },
    {
        "id": 116,
        "sku": "XEI-CEDOPAMINE-06",
        "name": "ESMALTE GEL OJO DE GATO AZUL DOPAMINA - 06",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1776805879_69e7e7f74d4c9.jpg",
        "description": "XEIJAYI 15ML GEL MAGNÉTICO SEMI PERMANENTE OJO DE GATO REFLECTANTE PARA UÑAS, ARTE DE UÑAS LED, GEL PARA SALÓN DE MANICURA DIY",
        "etiqueta": null
    },
    {
        "id": 117,
        "sku": "XEI-DREAMYSTAR-03",
        "name": "ESMALTE GEL OJO DE GATO AMARILLO DREAM STAR - 03",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1776805954_69e7e842d5603.jpg",
        "description": "XEIJAYI 15ML GEL MAGNÉTICO SEMI PERMANENTE OJO DE GATO REFLECTANTE PARA UÑAS, ARTE DE UÑAS LED, GEL PARA SALÓN DE MANICURA DIY",
        "etiqueta": null
    },
    {
        "id": 118,
        "sku": "GLOV-IMANESFR-02",
        "name": "IMAN PARA EFECTO OJO DE GATO DOBLE PUNTA CON ESFERA GOLD ROSE",
        "brand": "GLOVE",
        "price": 18,
        "categoryId": "5",
        "image": "1776806292_69e7e9949977b.jpg",
        "description": "JUEGO DE BOLAS MAGNÉTICAS DE ACERO PARA UÑAS CON MANGO LARGO DE ALUMINIO, DOBLE PUNTA, HERRAMIENTA MAGNÉTICA PARA ESMALTE DE UÑAS GEL, MANICURA Y EFECTO OJO DE GATO",
        "etiqueta": "DESTACADOS"
    },
    {
        "id": 119,
        "sku": "XEI-LUXCOFFEE-02",
        "name": "ESMALTE GEL OJO DE GATO MARRON CAFE LUXURY - 02",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1776817571_69e815a34b6cd.jpg",
        "description": "TENDENCIAS DE UÑAS OJO DE GATO 2026 ARTE DE UÑAS HOLOGRÁFICO 15ML GEL DE UÑAS MAGNÉTICO REFLECTANTE OJO DE GATO PARA REMOJO GEL LED SALÓN HERRAMIENTAS DE ARTE DE UÑAS FEMENINAS GEL DE UÑAS",
        "etiqueta": null
    },
    {
        "id": 120,
        "sku": "XEI-CEBLUEKLEIN-M204",
        "name": "ESMALTE GEL OJO DE GATO AZUL KLEIN - M204",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1776817731_69e816439ba1a.jpg",
        "description": "ESMALTE XEIJAYI DISEÑOS DE ARTE DE UÑAS HOLOGRÁFICOS DE OJO DE GATO DE MODA, 15 ML, GEL MAGNÉTICO REFLECTANTE DE OJO DE GATO PARA REMOJO, GEL LED PARA SALÓN",
        "etiqueta": null
    },
    {
        "id": 121,
        "sku": "XEI-CEPURPLE-09",
        "name": "ESMALTE GEL OJO DE GATO PURPURA - 09",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1776817844_69e816b41fc11.jpg",
        "description": "ESMALTE XEIJAYI DISEÑOS DE ARTE DE UÑAS HOLOGRÁFICOS DE OJO DE GATO DE MODA, 15 ML, GEL MAGNÉTICO REFLECTANTE DE OJO DE GATO PARA REMOJO, GEL LED PARA SALÓN",
        "etiqueta": null
    },
    {
        "id": 122,
        "sku": "XEI-SETGREENB",
        "name": "SET DE ESMALTES COLECCION VERDES X6",
        "brand": "XEIJAYI",
        "price": 65,
        "categoryId": "2",
        "image": "1776818118_69e817c66d934.jpg",
        "description": "DISEÑOS DE ARTE DE UÑAS HOLOGRÁFICOS DE OJO DE GATO DE MODA, 15 ML, GEL MAGNÉTICO REFLECTANTE DE OJO DE GATO PARA REMOJO, GEL LED PARA SALÓN - X037 - X039 - X047 - X012 - X016 - X024",
        "etiqueta": null
    },
    {
        "id": 123,
        "sku": "HER-SPJ002-BRILLANTE",
        "name": "TIJERAS PARA CUTÍCULAS",
        "brand": "GENERICO",
        "price": 12,
        "categoryId": "3",
        "image": "1776820065_69e81f6184298.jpg",
        "description": "TIJERAS PARA CUTÍCULAS, CORTA CUTÍCULAS, CORTA CUTÍCULAS DE ACERO INOXIDABLE, TIJERAS PARA ELIMINAR PIEL MUERTA, HERRAMIENTAS DE MANICURA",
        "etiqueta": null
    },
    {
        "id": 124,
        "sku": "GLOV-IMANESFRCIL-03",
        "name": "SET DE 2 IMANES MAGNÉTICOS PARA UÑAS (REDONDOS Y CILÍNDRICOS)",
        "brand": "GLOVE",
        "price": 8,
        "categoryId": "5",
        "image": "1776820398_69e820aed93af.jpg",
        "description": "SET DE 2 IMANES MAGNÉTICOS PARA UÑAS (REDONDOS Y CILÍNDRICOS) – LÁPIZ MAGNÉTICO PARA UÑAS, DISEÑO DE UÑAS, ADSORCIÓN MAGNÉTICA PARA SALÓN DE UÑAS Y USO DOMÉSTICO, DECORACIÓN MAGNÉTICA PARA UÑAS",
        "etiqueta": null
    },
    {
        "id": 125,
        "sku": "BRO-TUGS5N1-A",
        "name": "BROCA ACERO DE TUNGSTENO PROFESIONAL 5 EN 1",
        "brand": "GENERICO",
        "price": 14,
        "categoryId": "3",
        "image": "1776820620_69e8218c9e240.jpg",
        "description": "FRESAS DE ACERO DE TUNGSTENO PROFESIONALES 5 EN 1 PARA TALADRO DE UÑAS, CORTADOR DE FRESADO DE DIENTES CRUZADOS PARA MANICURA ELÉCTRICA, ACCESORIO DE HERRAMIENTA DE MANICURA PARA ELIMINACIÓN DE GEL",
        "etiqueta": null
    },
    {
        "id": 126,
        "sku": "BP-PREPARADS-02",
        "name": "BORN PRETTY 2 PCS 15 ML KIT DE PREPARACION DE UÑAS -  DESHIDRATADOR-PRIMER",
        "brand": "BORN PRETTY",
        "price": 36,
        "categoryId": "13",
        "image": "1777528096_69f2ed20df1d4.jpg",
        "description": "BORN PRETTY 2 PIEZAS 15ML KIT DE PREPARACIÓN DE UÑAS DESHIDRATADOR-PRIMER - 3S SECADO RÁPIDO EN EL AIRE, SIN ALCOHOL, DURADERA MÁS DE 28 DÍAS, PARA LIMPIEZA Y ELIMINACIÓN DE POLVO Y ACEITE DE UÑAS, CON FÓRMULA NATURAL PARA UÑAS SALUDABLES, ESENCIALES PARA EL CUIDADO DE LAS UÑAS | FÓRMULA DE SECADO RÁPIDO | FÓRMULA SIN ALCOHOL, KIT DE CUIDADO DE UÑAS",
        "etiqueta": null
    },
    {
        "id": 127,
        "sku": "GEN-LAMPARAUVPINK-DESING",
        "name": "LAMPARA UV DISEÑO TIPO LINTERNA - ROSADA",
        "brand": "GENERICO",
        "price": 20,
        "categoryId": "4",
        "image": "1777528344_69f2ee1829951.jpg",
        "description": "LÁMPARA DE UÑAS INALÁMBRICA \/ SECADORA CON PANTALLA LCD Y INTERRUPTOR DE BOTÓN - SET DE MANICURA Y PEDICURA RECARGABLE, ALIMENTADA POR USB, DISEÑO COMPACTO PARA USO EN CASA O SALÓN, LÁMPARA DE UÑAS PARA MANICURA, EQUIPO DE SALÓN, PLÁSTICO DURADERO",
        "etiqueta": null
    },
    {
        "id": 128,
        "sku": "XEI-CEBLUEGLACIAL-GS06",
        "name": "ESMALTE GEL OJO DE GATO AZUL GLACIAL - 06",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1777528468_69f2ee94e60bf.jpg",
        "description": "ESMALTE XEIJAYI DISEÑOS DE ARTE DE UÑAS HOLOGRÁFICOS DE OJO DE GATO DE MODA, 15 ML, GEL MAGNÉTICO REFLECTANTE DE OJO DE GATO PARA REMOJO, GEL LED PARA SALÓN",
        "etiqueta": null
    },
    {
        "id": 129,
        "sku": "XEI-CEPEACOK-04",
        "name": "ESMALTE GEL OJO DE GATO DUO TONO PAVO REAL - 04",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1777528647_69f2ef47d81c7.jpg",
        "description": "ESMALTE XEIJAYI DISEÑOS DE ARTE DE UÑAS HOLOGRÁFICOS DE OJO DE GATO DE MODA, 15 ML, GEL MAGNÉTICO REFLECTANTE DE OJO DE GATO PARA REMOJO, GEL LED PARA SALÓN",
        "etiqueta": null
    },
    {
        "id": 130,
        "sku": "MOCMAKI-GELPAINT-P21",
        "name": "GEL DE PINTURA DE 9 COLORES MARRONES MOCMAKI - SATURADOS",
        "brand": "JILLRADIA",
        "price": 32,
        "categoryId": "8",
        "image": "1777915281_69f8d591ca612.jpg",
        "description": "GEL DE PINTURA DEGRADADA, 9 COLORES DE ESMALTE DE UÑAS EN GEL OMBRÉ PARA UÑAS OMBRÉ Y UÑAS AURA, MANICURA FRANCESA, ARTE DE UÑAS DIY, SERIE DOPAMINA ARCOÍRIS, MODA PRIMAVERA VERANO 2025, BRILLO DE ALTA SATURACIÓN, REMOJO DURADERO DE LA PALETA SOLAR FLARE",
        "etiqueta": null
    },
    {
        "id": 131,
        "sku": "GEN-IMANANILLO2PCS",
        "name": "IMAN 2 PCS ANILLO - ESTILO HUECO FRANCÉS OJO DE GATO",
        "brand": "GENERICO",
        "price": 12,
        "categoryId": "5",
        "image": "1777915649_69f8d701df280.jpg",
        "description": "2 PIEZAS NUEVO ESTILO HUECO FRANCÉS OJO DE GATO DE ALTA BRILLANTEZ ANILLO DE UÑA IMÁN CUADRADO, FÁCIL OPERACIÓN, UNA FORMACIÓN DE COLOCACIÓN, ADECUADO PARA SALONES DE UÑAS Y PRODUCCIÓN ARTESANAL DE ENTUSIASTAS DE LAS UÑAS, HERRAMIENTA AUXILIAR DE UÑAS",
        "etiqueta": "DESTACADOS"
    },
    {
        "id": 132,
        "sku": "GEN-ESPONJAS-100PCSCLIP",
        "name": "SET DE 100 ESPONJAS Y CLIPS PARA UÑAS, ESPONJAS DEGRADADAS",
        "brand": "GENERICO",
        "price": 15,
        "categoryId": "3",
        "image": "1777915808_69f8d7a0ba0d5.jpg",
        "description": "SET DE 100 ESPONJAS Y CLIPS PARA UÑAS, ESPONJAS DEGRADADAS PARA CREAR ESTILOS DE UÑAS OMBRE, BLANCO PURO Y SIN PELUSA, IDEAL PARA NAIL ART, SALONES DE UÑAS Y FORMACIÓN EN MANICURA - BLOQUES DE ESPONJA SUAVES Y SIN PELUSA PARA APLICACIÓN DEGRADADA",
        "etiqueta": null
    },
    {
        "id": 133,
        "sku": "XEI-CEAURORARED-M129",
        "name": "ESMALTE GEL OJO DE GATO ROJO AURORA - M129",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1777917432_69f8ddf8280a4.jpg",
        "description": "ESMALTE XEIJAYI DISEÑOS DE ARTE DE UÑAS HOLOGRÁFICOS DE OJO DE GATO DE MODA, 15 ML, GEL MAGNÉTICO REFLECTANTE DE OJO DE GATO PARA REMOJO, GEL LED PARA SALÓN",
        "etiqueta": null
    },
    {
        "id": 134,
        "sku": "XEI-CEBUBLSWETSUM-M186",
        "name": "ESMALTE GEL OJO DE GATO ROSADO BUBBLE SWEET SUMMER - M186",
        "brand": "XEIJAYI",
        "price": 20,
        "categoryId": "12",
        "image": "1777917783_69f8df573f554.jpg",
        "description": "TENDENCIAS DE UÑAS EFECTO OJO DE GATO 2026, ARTE DE UÑAS HOLOGRÁFICO, 6 COLORES, 15 ML, GEL MAGNÉTICO REFLECTANTE EFECTO OJO DE GATO, GEL DE INMERSIÓN LED PARA SALÓN, HERRAMIENTAS DE ARTE DE UÑAS PARA MUJER, GEL DE UÑAS DE MODA",
        "etiqueta": null
    },
    {
        "id": 135,
        "sku": "XEI-SOFTGELGLUE-PEGA",
        "name": "PEGAMENTO PARA SOFTGEL XEIJAYI DE 15 ML",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "11",
        "image": "1777918680_69f8e2d86617f.jpg",
        "description": "PIEZA DE PARCHE ADHESIVO PARA UÑAS 15ML CON TECNOLOGÍA LED, REMOVIBLE EN INMERSIÓN, DISEÑO DE ARTE PARA UÑAS, MEJORA DE UÑAS EN CASA, GEL FOTOTERAPÉUTICO NUEVO",
        "etiqueta": null
    },
    {
        "id": 136,
        "sku": "GEN-CORTACUTICULA-JAPONES",
        "name": "CORTA CUTICULA COLOR JAPONES DOBLE RESORTE",
        "brand": "GENERICO",
        "price": 18,
        "categoryId": "3",
        "image": "1777942006_69f93df6f0af2.jpg",
        "description": "1 PIEZA DE CORTAÚÑAS PROFESIONAL DE QUERATINA, HERRAMIENTA RECORTADORA DE UÑAS DE DOBLE RESORTE - EL KIT DE CUIDADO DE UÑAS PERFECTO PARA PEDICURAS Y BELLEZA EN CASA\/SPA\/SALÓN, PEDICURAS, ARTE DE UÑAS EN CASA, RECORTADORA DE PRECISIÓN, DISEÑO DE DOBLE HOJA, RECORTADORA DE ALTA CALIDAD",
        "etiqueta": null
    },
    {
        "id": 137,
        "sku": "XEI-METALSILVER-MT02",
        "name": "ESMALTE EN GEL XEIJAYI METALIZADO PLATEADO - MT02",
        "brand": "XEIJAYI",
        "price": 20,
        "categoryId": "2",
        "image": "1777942992_69f941d054c9a.jpg",
        "description": "NUEVO GEL DE PINTURA DE ALTA DENSIDAD PARA DECORACIÓN DE UÑAS, CON PEGAMENTO METÁLICO ESPEJO PLATINO PLATEADO CON BRILLO DESLUMBRANTE, PERFECTO PARA SALONES DE BELLEZA Y DISEÑOS DE UÑAS",
        "etiqueta": null
    },
    {
        "id": 138,
        "sku": "XEI-SETCELUXURYCOFFEE",
        "name": "SET ESMALTES GEL OJO DE GATO LUXURY COFFEE",
        "brand": "XEIJAYI",
        "price": 75,
        "categoryId": "12",
        "image": "1777943318_69f9431624d53.jpg",
        "description": "SET DE ESMALTES DE UÑAS OJO DE GATO 6 COLORES 15ML ESMALTE DE UÑAS MAGNÉTICO REFLECTANTE OJO DE GATO PARA REMOJO GEL LED SALÓN HERRAMIENTAS DE ARTE DE UÑAS PARA MUJER MODA ARTE DE UÑAS HOLOGRÁFICO",
        "etiqueta": null
    },
    {
        "id": 139,
        "sku": "GEN-POLVESPEJO-HOLOGRAFIC",
        "name": "POLVO HOLOGRÁFICO DE UNICORNIO ARCOÍRIS",
        "brand": "GENERICO",
        "price": 9,
        "categoryId": "7",
        "image": "1777943743_69f944bf076b4.jpg",
        "description": "POLVO HOLOGRÁFICO DE UNICORNIO ARCOÍRIS - POLVO DE PURPURINA CON EFECTO ESPEJO PARA ARTE DE UÑAS DIY",
        "etiqueta": null
    },
    {
        "id": 140,
        "sku": "XEI-TOPCOATCLEAR-15ML",
        "name": "XEIJAYI TOP COAT SUPER GLASS TRANSPARENTE - PRESENTACION 15 ML",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "11",
        "image": "1778020974_69fa726e09d06.jpg",
        "description": "XEIJAYI 1 PIEZA 15ML GEL DE ACABADO BRILLANTE Y REMOVIBLE CON LÁMPARA LED - PERFECTO PARA DISEÑO EN UÑAS",
        "etiqueta": null
    },
    {
        "id": 141,
        "sku": "XEI-SETREDSB",
        "name": "SET DE ESMALTES COLECCION ROJOS X6",
        "brand": "XEIJAYI",
        "price": 65,
        "categoryId": "2",
        "image": "1778021257_69fa7389a4dce.jpg",
        "description": "ESMALTE DE UÑAS LED DE REMOJO DE 15 ML, SET DE 6 COLORES PARA MANICURA DE TEMPORADA DE VERANO, HERRAMIENTAS DE MANICURA PARA SALÓN DE UÑAS PARA MUJER, MODA PARA LAS CUATRO ESTACIONES X017 - X025 - X026 - X027 - X036 -X044",
        "etiqueta": null
    },
    {
        "id": 142,
        "sku": "XEI-SETCESPARKLINGVIVID",
        "name": "SET DE ESMALTES EFECTO OJO DE GATO COLECCION BRILLANTE VIVIDO X6",
        "brand": "XEIJAYI",
        "price": 75,
        "categoryId": "12",
        "image": "1778022121_69fa76e980fc8.jpg",
        "description": "SET DE ESMALTE DE UÑAS EFECTO OJO DE GATO DE 6 PIEZAS DE 15 ML, GEL MAGNÉTICO REFLECTANTE DE OJO DE GATO PARA INMERSIÓN, GEL LED PARA SALÓN, HERRAMIENTAS DE ARTE DE UÑAS PARA MUJER, ARTE DE UÑAS HOLOGRÁFICO DE MODA",
        "etiqueta": null
    },
    {
        "id": 143,
        "sku": "XEI-CEPINKGRATPEF",
        "name": "ESMALTE GEL OJO DE GATO PINK GRAPEFRUIT",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1778026503_69fa880799f7c.jpg",
        "description": "DISEÑOS DE ARTE DE UÑAS HOLOGRÁFICOS DE OJO DE GATO DE MODA, 15 ML, GEL MAGNÉTICO REFLECTANTE DE OJO DE GATO PARA REMOJO, GEL LED PARA SALÓN",
        "etiqueta": null
    },
    {
        "id": 144,
        "sku": "JILLRADIA-GELPAINT-CACAO",
        "name": "GEL DE PINTURA DE 9 COLORES MARRONES JILLRADIA - CACAO CARAMEL",
        "brand": "JILLRADIA",
        "price": 32,
        "categoryId": "8",
        "image": "1778026671_69fa88af9c62a.jpg",
        "description": "JILLRADIA 9 COLORES PEGAMENTO PARA MASAJE, LÁPIZ LABIAL EN LATA DE ALTA SATURACIÓN, POPULAR, SEMI-SÓLIDO, PEGAMENTO PARA UÑAS, MANICURA PARA SALÓN DE BELLEZA",
        "etiqueta": null
    },
    {
        "id": 145,
        "sku": "XEI-FIBRUBGEL-100ML",
        "name": "XEIJAYI FIBER GEL BASE RUBBER 100 ML",
        "brand": "XEIJAYI",
        "price": 50,
        "categoryId": "11",
        "image": "1778027094_69fa8a56d50c6.jpg",
        "description": "XEIJAYI 1 PIEZA DE GEL DE FIBRA PARA UÑAS DE 100 ML PARA UÑAS ROTAS, GEL TRANSPARENTE PARA UÑAS, FORTALECEDOR DE UÑAS EN GEL PARA UÑAS DELGADAS",
        "etiqueta": null
    },
    {
        "id": 146,
        "sku": "XEI-SETROJOSA-X6",
        "name": "SET DE ESMALTES COLORES ROJOS COLECCION PASION X6",
        "brand": "XEIJAYI",
        "price": 65,
        "categoryId": "2",
        "image": "1778032451_69fa9f4323af2.jpg",
        "description": "JUEGO DE 6 ESMALTES DE UÑAS EN GEL DE 15 ML, KITS DE ESMALTE EN GEL SEMIPERMANENTE PARA MANICURA, REMOVIBLE CON REMOJO, PARA LED, ARTE DE UÑAS DIY, PARA SALÓN EN CASA, REGALO PARA MUJERES - 6PCS(80+81+82+105+77+FRAMBUESA)",
        "etiqueta": null
    },
    {
        "id": 147,
        "sku": "XEI-CELUCKYYELLOW",
        "name": "ESMALTE GEL OJO DE GATO AMARILLO DE LA SUERTE",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1778032716_69faa04c02e73.jpg",
        "description": "DISEÑOS DE ARTE DE UÑAS HOLOGRÁFICOS DE OJO DE GATO DE MODA, 15 ML, GEL MAGNÉTICO REFLECTANTE DE OJO DE GATO PARA REMOJO, GEL LED PARA SALÓN",
        "etiqueta": null
    },
    {
        "id": 148,
        "sku": "XEI-CELUXCOFF-05",
        "name": "ESMALTE GEL OJO DE GATO MARRON CAFE LUXURY - 03",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1778032820_69faa0b442d63.jpg",
        "description": "XEIJAYI 15ML GEL MAGNÉTICO SEMI PERMANENTE OJO DE GATO REFLECTANTE PARA UÑAS, ARTE DE UÑAS LED, GEL PARA SALÓN DE MANICURA DIY",
        "etiqueta": null
    },
    {
        "id": 149,
        "sku": "XEI-CEROMANTICTIME-16",
        "name": "ESMALTE GEL OJO DE GATO DORADO ROMANCE 16",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1778032925_69faa11d9d846.jpg",
        "description": "DISEÑOS DE ARTE DE UÑAS HOLOGRÁFICOS DE OJO DE GATO DE MODA, 15 ML, GEL MAGNÉTICO REFLECTANTE DE OJO DE GATO PARA REMOJO, GEL LED PARA SALÓN",
        "etiqueta": null
    },
    {
        "id": 150,
        "sku": "XEI-CEGOLDEN03",
        "name": "ESMALTE EN GEL OJO DE GATO DORADO GOLDEN 03",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1778274096_69fe4f3046b61.jpg",
        "description": "ESMALTE EN GEL EFECTO OJO DE GATO DORADO GOLDEN 03 PRESENTACION 15 ML",
        "etiqueta": null
    },
    {
        "id": 151,
        "sku": "HER-DRILL45KRPMPRO-BLA",
        "name": "PULIDORA DE UÑAS PROFESIONAL 45.000 RPM - BLANCO",
        "brand": "GENERICO",
        "price": 145,
        "categoryId": "3",
        "image": "1778288587_69fe87cbc0032.jpg",
        "description": "MÁQUINA ELÉCTRICA PULIDORA PARA UÑAS DE 45000 RPM CON PANTALLA HD, LIMA ELÉCTRICA, PLUMA DE MANICURA DE METAL, TORNO PROFESIONAL PARA UÑAS, LIJADORA, DRILL",
        "etiqueta": "DESTACADOS"
    },
    {
        "id": 152,
        "sku": "XEI-CESMOKESCREEN-M214",
        "name": "ESMALTE EN GEL OJO DE GATO CORTINA DE HUMO - M214",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1778288913_69fe8911711e3.jpg",
        "description": "ESMALTE EN GEL EFECTO OJO DE GATO MARRON DORADO M214 -  PRESENTACION 15 ML",
        "etiqueta": null
    },
    {
        "id": 153,
        "sku": "XEI-BROWNBLUE-M161",
        "name": "ESMALTE GEL OJO DE GATO MARRON AZUL - M161",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1778289012_69fe89741a33c.jpg",
        "description": "ESMALTE EN GEL EFECTO OJO DE GATO AZUL MARRON DUO COLOR - M161",
        "etiqueta": null
    },
    {
        "id": 154,
        "sku": "XEI-CEMAMBOMINT-M153",
        "name": "ESMALTE GEL OJO DE GATO MAMBO MENTA - M153",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1778289154_69fe8a02da4b0.jpg",
        "description": "ESMALTE EN GEL EFECTO OJO DE GATO VERDE MAMBO - M153 - OJO DE GATO VERDE",
        "etiqueta": null
    },
    {
        "id": 155,
        "sku": "HER-DRILL35KRPMMED-ROS",
        "name": "PULIDORA DE UÑAS PROFESIONAL 35.000 RPM - ROSADA",
        "brand": "GENERICO",
        "price": 125,
        "categoryId": "3",
        "image": "1778294700_69fe9fac95d6c.jpg",
        "description": "MÁQUINA ELÉCTRICA PULIDORA PARA UÑAS DE 35000 RPM CON PANTALLA HD, LIMA ELÉCTRICA, PLUMA DE MANICURA DE METAL, TORNO PROFESIONAL PARA UÑAS, LIJADORA, DRILL",
        "etiqueta": "DESTACADOS"
    },
    {
        "id": 156,
        "sku": "XEIM002-BASEWHITE",
        "name": "ESMALTE EN GEL BLANCO BASE XEIJAYI - M002",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1778350780_69ff7abccf23d.jpg",
        "description": "ESMALTE EN GEL XEIJAYI BLANCO BASE XEIJAYI - M002",
        "etiqueta": null
    },
    {
        "id": 157,
        "sku": "XEIM003-BASENUDE",
        "name": "ESMALTE EN GEL BASE NUDE XEIJAYI - M003",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1778351065_69ff7bd945f75.jpg",
        "description": "ESMALTE EN GEL BASE NUDE XEIJAYI - M003",
        "etiqueta": null
    },
    {
        "id": 158,
        "sku": "XEIM007-BASENUDE",
        "name": "ESMALTE EN GEL NUDE BASE XEIJAYI - M007",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1778351222_69ff7c767547e.jpg",
        "description": "ESMALTE EN GEL XEIJAYI NUDE BASE XEIJAYI - M007",
        "etiqueta": null
    },
    {
        "id": 159,
        "sku": "XEIM008-ROSEPALEPINK",
        "name": "ESMALTE EN GEL BASE PALO ROSA XEIJAYI - M008",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1778351437_69ff7d4dbae6c.jpg",
        "description": "ESMALTE EN GEL XEIJAYI BASE PALO ROSA XEIJAYI - M008",
        "etiqueta": null
    },
    {
        "id": 160,
        "sku": "XEIM010-ROSEPALEPINK",
        "name": "ESMALTE EN GEL BASE PALO ROSA XEIJAYI - M010",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1778351569_69ff7dd16398b.jpg",
        "description": "ESMALTE EN GEL XEIJAYI BASE PALO ROSA XEIJAYI - M010",
        "etiqueta": null
    },
    {
        "id": 161,
        "sku": "XEIM014-ROSEPINK",
        "name": "ESMALTE EN GEL BASE ROSA PINK XEIJAYI - M014",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1778351696_69ff7e5034d40.jpg",
        "description": "ESMALTE EN GEL XEIJAYI BASE ROSA PINK XEIJAYI - M014",
        "etiqueta": null
    },
    {
        "id": 162,
        "sku": "XEIM015-NUDEROSE",
        "name": "ESMALTE EN GEL BASE NUDE ROSE XEIJAYI - M015",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1778351930_69ff7f3aa4800.jpg",
        "description": "ESMALTE EN GEL XEIJAYI BASE ROSA PINK XEIJAYI - M015",
        "etiqueta": null
    },
    {
        "id": 163,
        "sku": "XEIM017-NUDEICE",
        "name": "ESMALTE EN GEL BASE NUDE ICE XEIJAYI - M017",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1778352062_69ff7fbe26585.jpg",
        "description": "ESMALTE EN GEL XEIJAYI BASE NUDE ICE XEIJAYI - M017",
        "etiqueta": null
    },
    {
        "id": 164,
        "sku": "XEI-CEGREEN-M202",
        "name": "ESMALTE GEL OJO DE GATO VERDE GEMA - M202",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1778808858_6a06781a5cef7.jpg",
        "description": "ESMALTE XEIJAYI DISEÑOS DE ARTE DE UÑAS HOLOGRÁFICOS DE OJO DE GATO DE MODA, 15 ML, GEL MAGNÉTICO REFLECTANTE DE OJO DE GATO PARA REMOJO, GEL LED PARA SALÓN M202",
        "etiqueta": "DESTACADOS"
    },
    {
        "id": 166,
        "sku": "XEI-CEGREEN-BAMBU2",
        "name": "ESMALTE GEL OJO DE GATO VERDE BAMBU 02",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1778809057_6a0678e1eb6bd.jpg",
        "description": "ESMALTE XEIJAYI DISEÑOS DE ARTE DE UÑAS HOLOGRÁFICOS DE OJO DE GATO DE MODA, 15 ML, GEL MAGNÉTICO REFLECTANTE DE OJO DE GATO PARA REMOJO, GEL LED PARA SALÓN",
        "etiqueta": null
    },
    {
        "id": 167,
        "sku": "XEIM006-BASENUDE",
        "name": "ESMALTE EN GEL NUDE BASE XEIJAYI - M006",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1779133980_6a0b6e1ce74e4.jpg",
        "description": "ESMALTE EN GEL XEIJAYI NUDE BASE XEIJAYI - M006",
        "etiqueta": null
    },
    {
        "id": 169,
        "sku": "XEIM005-BASENUDE",
        "name": "ESMALTE EN GEL NUDE BASE XEIJAYI - M005",
        "brand": "XEIJAYI",
        "price": 15,
        "categoryId": "2",
        "image": "1779134525_6a0b703d25fd7.jpg",
        "description": "ESMALTE EN GEL NUDE BASE XEIJAYI - M005",
        "etiqueta": null
    },
    {
        "id": 170,
        "sku": "XEI-SETLPURPLEB",
        "name": "SET DE ESMALTES COLECCION LILAS X6",
        "brand": "XEIJAYI",
        "price": 65,
        "categoryId": "2",
        "image": "1779329730_6a0e6ac2eb2bb.jpg",
        "description": "DISEÑOS DE ARTE DE UÑAS, 15 ML, COLECCION ESMALTES EN GEL MORADOS PARA SALÓN - X048 - X051 - X052 - X053 - X054 - X055",
        "etiqueta": null
    },
    {
        "id": 171,
        "sku": "XEIX023-MAGENTAPURPLE",
        "name": "ESMALTE EN GEL XEIJAYI MORADO MAGENTA 15ML",
        "brand": "XEIJAYI",
        "price": 14,
        "categoryId": "2",
        "image": "1779330295_6a0e6cf747061.jpg",
        "description": "XEIJAYI Gel de uñas semipermanente de 15 ml, nuevo y popular, para arte de uñas, remojo LED, para salón de uñas - X023",
        "etiqueta": null
    },
    {
        "id": 173,
        "sku": "XEIX048",
        "name": "ESMALTE EN GEL XEIJAYI LILA 15ML",
        "brand": "XEIJAYI",
        "price": 14,
        "categoryId": "2",
        "image": "1779330544_6a0e6df0870c0.jpg",
        "description": "XEIJAYI Gel de uñas semipermanente de 15 ml, nuevo y popular, para arte de uñas, remojo LED, para salón de uñas - X048",
        "etiqueta": null
    },
    {
        "id": 174,
        "sku": "XEIX051-DARKPURPLE",
        "name": "ESMALTE EN GEL XEIJAYI PURPURA OSCURO 15ML",
        "brand": "XEIJAYI",
        "price": 14,
        "categoryId": "2",
        "image": "1779330722_6a0e6ea29037d.jpg",
        "description": "XEIJAYI Gel de uñas semipermanente de 15 ml, nuevo y popular, para arte de uñas, remojo LED, para salón de uñas - X051",
        "etiqueta": null
    },
    {
        "id": 175,
        "sku": "XEIX052",
        "name": "ESMALTE EN GEL XEIJAYI MORADO VITRAL 15ML",
        "brand": "XEIJAYI",
        "price": 14,
        "categoryId": "2",
        "image": "1779330841_6a0e6f1949b88.jpg",
        "description": "XEIJAYI Gel de uñas semipermanente de 15 ml, nuevo y popular, para arte de uñas, remojo LED, para salón de uñas - X052",
        "etiqueta": null
    },
    {
        "id": 176,
        "sku": "XEIX053-DARKLILA",
        "name": "ESMALTE EN GEL XEIJAYI LILA OSCURO 15ML",
        "brand": "XEIJAYI",
        "price": 14,
        "categoryId": "2",
        "image": "1779330963_6a0e6f93dfc71.jpg",
        "description": "XEIJAYI Gel de uñas semipermanente de 15 ml, nuevo y popular, para arte de uñas, remojo LED, para salón de uñas - X053",
        "etiqueta": null
    },
    {
        "id": 177,
        "sku": "XEIX054-LILAPINK",
        "name": "ESMALTE EN GEL XEIJAYI LILA PINK 15ML",
        "brand": "XEIJAYI",
        "price": 14,
        "categoryId": "2",
        "image": "1779331103_6a0e701f6f817.jpg",
        "description": "XEIJAYI Gel de uñas semipermanente de 15 ml, nuevo y popular, para arte de uñas, remojo LED, para salón de uñas - X054",
        "etiqueta": null
    },
    {
        "id": 178,
        "sku": "XEIX055-LILAGRAY",
        "name": "ESMALTE EN GEL XEIJAYI LILA GRAY 15ML",
        "brand": "XEIJAYI",
        "price": 14,
        "categoryId": "2",
        "image": "1779331189_6a0e70756033d.jpg",
        "description": "XEIJAYI Gel de uñas semipermanente de 15 ml, nuevo y popular, para arte de uñas, remojo LED, para salón de uñas - X055",
        "etiqueta": null
    },
    {
        "id": 179,
        "sku": "XEIX017-REDVITRAL",
        "name": "ESMALTE EN GEL XEIJAYI ROJO VITRAL 15ML",
        "brand": "XEIJAYI",
        "price": 14,
        "categoryId": "2",
        "image": "1779331515_6a0e71bb608e9.jpg",
        "description": "XEIJAYI Gel de uñas semipermanente de 15 ml, nuevo y popular, para arte de uñas, remojo LED, para salón de uñas - X017",
        "etiqueta": null
    },
    {
        "id": 180,
        "sku": "POLVO-AURORA-GEN",
        "name": "POLVO EFECTO AURORA PARA UÑAS",
        "brand": "GENERICO",
        "price": 9,
        "categoryId": "7",
        "image": "1779375622_6a0f1e0678a9d.jpg",
        "description": "POLVO DE ARCOÍRIS PARA UÑAS, POLVO AURORA ILUSORIA, POLVO LUZ LUNAR, POLVO ESPEJO MÁGICO: COMBINA CON DIVERSOS COLORES BASE PARA TONOS POLARIZADOS Y RESPLANDECIENTES",
        "etiqueta": null
    },
    {
        "id": 181,
        "sku": "XEI-CEGOLDEN02",
        "name": "ESMALTE EN GEL OJO DE GATO DORADO GOLDEN 02",
        "brand": "XEIJAYI",
        "price": 18,
        "categoryId": "12",
        "image": "1779376842_6a0f22ca9f14b.jpg",
        "description": "ESMALTE EN GEL EFECTO OJO DE GATO DORADO GOLDEN 02 PRESENTACION 15 ML",
        "etiqueta": null
    },
    {
        "id": 182,
        "sku": "XEIR019-VITRALNEGRO",
        "name": "ESMALTE EN GEL XEIJAYI VITRAL NEGRO 15ML",
        "brand": "XEIJAYI",
        "price": 17,
        "categoryId": "2",
        "image": "1779377548_6a0f258c3626a.jpg",
        "description": "XEIJAYI 1PC ESMALTE DE UÑAS EN GEL , 15ML, ARTE DE UÑAS PARA TODAS LAS ESTACIONES, ESMALTE LED REMOVIBLE CON INMERSIÓN, MANICURA DIY PARA HOGAR Y SALÓN",
        "etiqueta": null
    },
    {
        "id": 183,
        "sku": "XEI-SETCESILK",
        "name": "SET DE ESMALTES EFECTO OJO DE GATO COLECCION SEDA X6",
        "brand": "XEIJAYI",
        "price": 75,
        "categoryId": "12",
        "image": "1779400068_6a0f7d842ec87.jpg",
        "description": "SET DE ESMALTES EFECTO OJO DE GATO COLECCION SEDA VIVIDO X6 ROSADO MORADO NUDE M117 - WATER MIRROR 05 - HAITANG CHUNG 07 - HAITANG CHUNG 08 - NINE PURPLE 02 - M135",
        "etiqueta": null
    },
    {
        "id": 184,
        "sku": "SUTOZMIWE-GELPAINT-P21",
        "name": "GEL DE PINTURA DE 9 COLORES SUTOZMIWE - P21",
        "brand": "SUTOZMIWE",
        "price": 30,
        "categoryId": "8",
        "image": "1779401065_6a0f81696f7ca.jpg",
        "description": "9 COLORES SUTOZMIWE, COLORES DE OTOÑO E INVIERNO, RUBOR EN POLVO DEGRADADO, PINTURA MANUAL, SIN NECESIDAD DE LAVAR, ALTA SATURACIÓN, GEL DE MANCHAS DE COLOR GRUESO, DISEÑADO PARA MEJORAR UÑAS",
        "etiqueta": "DESTACADOS"
    },
    {
        "id": 185,
        "sku": "SUTOZMIWE-GELPAINT-P02",
        "name": "GEL DE PINTURA DE 9 COLORES SUTOZMIWE - P02",
        "brand": "SUTOZMIWE",
        "price": 30,
        "categoryId": "8",
        "image": "1779401197_6a0f81ed2d62f.jpg",
        "description": "9 COLORES SUTOZMIWE, COLORES DE OTOÑO E INVIERNO, RUBOR EN POLVO DEGRADADO, PINTURA MANUAL, SIN NECESIDAD DE LAVAR, ALTA SATURACIÓN, GEL DE MANCHAS DE COLOR GRUESO, DISEÑADO PARA MEJORAR UÑAS",
        "etiqueta": "DESTACADOS"
    }
];
